"""Flat wall rig: 77m x 21m screen, rounded corners, sweet spot 35m.

Standalone:  python Scripts/round.py   -> writes nDisplay/Round_1Screen.ndisplay + Run_Round.bat
In editor:   Rebuild_Round.bat         -> also places the rig + demo content in Round.umap
Variants:    round_video.py / Rebuild_RoundVideo.bat / Run_RoundVideo.bat override the
             knobs below and reuse everything else.

Geometry: world origin = viewer's EYE, +X toward the wall, +Y right, +Z up. Units cm.
The rounded corners do not change the frustum (the Screen component is always a
plain rectangle). They are applied as an nDisplay *Output Remap* mesh: a rounded
rectangle .obj is normalized to the node's window, and everything outside it is
black -- exactly like the LED panel having no pixels there.
"""
import json, math, os

# --- knobs (mm on the drawing -> cm here) ----------------------------------
SCREEN_W_CM = 7700.0        # 77000 mm
SCREEN_H_CM = 2100.0        # 21000 mm
EYE_DIST_CM = 3500.0        # 35000 mm sweet spot, eye -> wall
CORNER_RADIUS_CM = 300.0    # ponytail: guessed, drawing does not say
EYE_HEIGHT_CM = 160.0       # eye above the floor; wall bottom edge sits on the floor
SCREEN_DZ_CM = SCREEN_H_CM / 2.0 - EYE_HEIGHT_CM   # wall center relative to eye

RES_W = 2560                                       # test window on one desktop monitor
RES_H = int(round(RES_W * SCREEN_H_CM / SCREEN_W_CM))  # keep 77:21
WIN_X, WIN_Y = 0, 0
FOLLOW_PLAYER = False

RIG_ORIGIN = (0.0, 0.0, EYE_HEIGHT_CM)   # eye, when the level has no DCRA yet
DEMO = True                              # parallax cubes + back wall behind the screen
DEMO_DEPTH_CM = 6000.0
ROUNDED = True          # False: plain rectangle (no output remap mask)
VIDEO = ""              # relative to project, e.g. "Content/Movies/MediaExample_wall.mp4"; "" = no media plate.
                        # Any aspect: the plate fills the wall, so use a 77:21 file
                        # (convert_video.py) unless you want it stretched.
PLATE_YAW = 0.0         # flip to 180 if the wall renders black (plate mesh is one-sided)

UE_EXE = r"D:\Epic Games\UE_5.8\Engine\Binaries\Win64\UnrealEditor.exe"
MAP = "/Game/VprodProject/Maps/Round"   # created by the Rebuild bat if missing
BAT = "Run_Round.bat"

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
CFG_PATH = os.path.join(ROOT, "nDisplay", "Round_1Screen.ndisplay")
MASK_PATH = os.path.join(ROOT, "nDisplay", "Round_Mask.obj")
CORNER_SEGMENTS = 16
ASSET_DIR, ASSET_NAME = "/Game/Round", "NDC_Round_1Screen"
EYE_NAME, SCREEN_NAME = "DefaultViewPoint", "screen_0"


def rounded_rect():
    """-> [(x, y)] in cm, centre origin, CCW, corners as arcs. Convex, so a fan works."""
    W, H, R = SCREEN_W_CM / 2, SCREEN_H_CM / 2, CORNER_RADIUS_CM
    pts = []
    for cx, cy, a0 in ((W - R, -H + R, -90), (W - R, H - R, 0), (-W + R, H - R, 90), (-W + R, -H + R, 180)):
        for i in range(CORNER_SEGMENTS + 1):
            a = math.radians(a0 + 90.0 * i / CORNER_SEGMENTS)
            pts.append((cx + R * math.cos(a), cy + R * math.sin(a)))
    return pts


def build_mask_obj():
    """nDisplay OBJ loader: position (X,-Y,Z), screen X = Y axis, screen Y = Z axis,
    mesh AABB is normalized to the whole window; UVs must be 0..1 (bottom-up)."""
    W, H = SCREEN_W_CM / 2, SCREEN_H_CM / 2
    pts = rounded_rect()
    lines = ["# rounded-rect output remap mask, generated by round.py"]
    lines += ["v 0 %.4f %.4f" % (-x, y) for x, y in pts]
    lines += ["vt %.6f %.6f" % ((x + W) / (2 * W), (y + H) / (2 * H)) for x, y in pts]
    lines.append("f " + " ".join("%d/%d" % (i + 1, i + 1) for i in range(len(pts))))
    return "\n".join(lines) + "\n"


def build_config():
    return {"nDisplay": {
        "description": "Flat 77x21m wall, single viewport",
        "version": "5.00",
        "assetPath": "%s/%s.%s" % (ASSET_DIR, ASSET_NAME, ASSET_NAME),
        "misc": {"bFollowLocalPlayerCamera": FOLLOW_PLAYER, "bExitOnEsc": True,
                 "bOverrideViewportsFromExternalConfig": True,
                 "bOverrideTransformsFromExternalConfig": True},
        "scene": {
            "cameras": {EYE_NAME: {
                "parentId": "", "location": {"x": 0.0, "y": 0.0, "z": 0.0},
                "rotation": {"pitch": 0.0, "yaw": 0.0, "roll": 0.0},
                "interpupillaryDistance": 6.4, "swapEyes": False, "stereoOffset": "None"}},
            "screens": {SCREEN_NAME: {
                "parentId": "", "location": {"x": EYE_DIST_CM, "y": 0.0, "z": SCREEN_DZ_CM},
                "rotation": {"pitch": 0.0, "yaw": 0.0, "roll": 0.0},
                "size": {"width": SCREEN_W_CM, "height": SCREEN_H_CM}}}},
        "cluster": {
            "primaryNode": {"id": "node_0"},
            "sync": {"renderSyncPolicy": {"type": "none", "parameters": {}},
                     "inputSyncPolicy": {"type": "None", "parameters": {}}},
            "nodes": {"node_0": {
                "host": "127.0.0.1", "sound": True, "fullScreen": False,
                "window": {"x": WIN_X, "y": WIN_Y, "w": RES_W, "h": RES_H},
                "outputRemap": {"bEnable": ROUNDED, "dataSource": "file", "externalFile": MASK_PATH},
                "viewports": {"vp_0": {
                    "camera": EYE_NAME,
                    "region": {"x": 0, "y": 0, "w": RES_W, "h": RES_H},
                    "projectionPolicy": {"type": "mesh",
                                         "parameters": {"mesh_component": SCREEN_NAME}}}}}},
        },
    }}


def build_bat():
    lines = [
        "@echo off",
        "rem Requires: display scaling 100%, taskbar set to auto-hide (see anamorphic.py).",
        '"%s" "%s" %s ^' % (UE_EXE, os.path.join(ROOT, "Moniter_2.uproject"), MAP),
        ' -game -dc_cluster -dc_dev_mono -dc_node=node_0 -dc_cfg="%%~dp0%s" ^'
        % os.path.relpath(CFG_PATH, ROOT),
        " -windowed -forceres WinX=%d WinY=%d ResX=%d ResY=%d ^" % (WIN_X, WIN_Y, RES_W, RES_H),
        " -nosplash -fixedseed -NoVerifyGC -unattended",
    ]
    return "\r\n".join(lines) + "\r\n"


def demo():
    cfg = build_config()["nDisplay"]
    s = cfg["scene"]["screens"][SCREEN_NAME]
    assert s["location"]["z"] - SCREEN_H_CM / 2.0 == -EYE_HEIGHT_CM, "wall bottom is not on the floor"
    assert abs(RES_W / RES_H - SCREEN_W_CM / SCREEN_H_CM) < 0.01, "window aspect != wall aspect"
    assert 2 * CORNER_RADIUS_CM <= SCREEN_H_CM, "corner radius too big"
    assert "ResX=%d" % RES_W in build_bat()
    pts = rounded_rect()
    W, H = SCREEN_W_CM / 2, SCREEN_H_CM / 2
    assert max(abs(x) for x, _ in pts) == W and max(abs(y) for _, y in pts) == H, "mask AABB != wall"
    obj = build_mask_obj()
    assert all(0.0 <= float(t) <= 1.0 for l in obj.splitlines() if l.startswith("vt ") for t in l.split()[1:]), "UV outside 0..1"
    if ROUNDED:
        assert CORNER_RADIUS_CM > 0, "ROUNDED needs CORNER_RADIUS_CM > 0 (else use ROUNDED=False)"
        assert all(abs(x) < W - 1e-6 or abs(y) < H - 1e-6 for x, y in pts), "mask corners are not rounded"
    print("geometry ok: wall %gx%g cm at %g cm, %s corners, window %dx%d"
          % (SCREEN_W_CM, SCREEN_H_CM, EYE_DIST_CM,
             ("r%g" % CORNER_RADIUS_CM) if ROUNDED else "square", RES_W, RES_H))


def build_level():
    import unreal
    actors = unreal.get_editor_subsystem(unreal.EditorActorSubsystem)
    keep_transform = None
    for a in actors.get_all_level_actors():
        if isinstance(a, unreal.DisplayClusterRootActor):
            keep_transform = (a.get_actor_location(), a.get_actor_rotation())
            actors.destroy_actor(a)
        elif a.get_actor_label().startswith("RND_"):
            actors.destroy_actor(a)

    asset = "%s/%s" % (ASSET_DIR, ASSET_NAME)
    if not unreal.EditorAssetLibrary.does_asset_exist(asset):
        task = unreal.AssetImportTask()
        task.filename, task.destination_path, task.destination_name = CFG_PATH, ASSET_DIR, ASSET_NAME
        task.automated = task.replace_existing = task.save = True
        unreal.AssetToolsHelpers.get_asset_tools().import_asset_tasks([task])

    O = unreal.Vector(*RIG_ORIGIN)
    cube = unreal.load_object(None, "/Engine/BasicShapes/Cube.Cube")
    cyl = unreal.load_object(None, "/Engine/BasicShapes/Cylinder.Cylinder")
    grid = unreal.load_object(None, "/Engine/EngineMaterials/WorldGridMaterial.WorldGridMaterial")

    def spawn(mesh, name, loc, size, rot=(0, 0, 0), hidden=False):
        act = actors.spawn_actor_from_object(mesh, unreal.Vector(*loc) + O,
                                             unreal.Rotator(roll=rot[0], pitch=rot[1], yaw=rot[2]))
        act.set_actor_label("RND_" + name)
        act.set_actor_scale3d(unreal.Vector(*[v / 100.0 for v in size]))
        act.static_mesh_component.set_material(0, grid)
        # The frame sits ON the screen plane, so it would render over the wall content.
        act.set_actor_hidden_in_game(hidden)
        return act

    # Reference frame of the physical wall: 4 edge bars (shortened by the corner
    # radius) + 4 corner discs, so the rounded outline is visible in the editor.
    # Square corners (ROUNDED=False): full-length bars, no discs.
    R = CORNER_RADIUS_CM if ROUNDED else 0.0
    t, X, W, H = 20.0, EYE_DIST_CM, SCREEN_W_CM / 2, SCREEN_H_CM / 2
    spawn(cube, "top",    (X, 0, SCREEN_DZ_CM + H), (t, 2 * (W - R), t), hidden=True)
    spawn(cube, "bottom", (X, 0, SCREEN_DZ_CM - H), (t, 2 * (W - R), t), hidden=True)
    spawn(cube, "left",   (X, -W, SCREEN_DZ_CM),    (t, t, 2 * (H - R)), hidden=True)
    spawn(cube, "right",  (X,  W, SCREEN_DZ_CM),    (t, t, 2 * (H - R)), hidden=True)
    for i, (sy, sz) in enumerate(((-1, 1), (1, 1), (-1, -1), (1, -1)) if R else ()):
        # ponytail: a disc at the arc centre, not a real arc. Marks where the panel ends.
        spawn(cyl, "corner%d" % i, (X, sy * (W - R), SCREEN_DZ_CM + sz * (H - R)),
              (2 * R, 2 * R, t), rot=(0, 90, 0), hidden=True)

    if DEMO:
        x1 = EYE_DIST_CM + DEMO_DEPTH_CM
        k = x1 / EYE_DIST_CM   # widest ray, out to the back wall
        y, z = (W + 200) * k, (H + 200) * k
        spawn(cube, "back",  (x1, 0, SCREEN_DZ_CM), (t, 2 * y, 2 * z))
        spawn(cube, "floor", ((EYE_DIST_CM + x1) / 2, 0, -EYE_HEIGHT_CM - t / 2), (DEMO_DEPTH_CM, 2 * y, t))
        for i, (dx, dy, dz, s) in enumerate(((800, -2000, 0, 300), (1500, 0, 600, 400),
                                             (2500, 2200, -100, 500), (4500, -1000, 300, 800))):
            spawn(cube, "cue%d" % i, (EYE_DIST_CM + dx, dy, dz), (s, s, s))

    if VIDEO:
        # MediaPlate auto-plays on BeginPlay; sits exactly on the screen plane, fills it.
        plate = actors.spawn_actor_from_class(
            unreal.MediaPlate, unreal.Vector(EYE_DIST_CM, 0, SCREEN_DZ_CM) + O,
            unreal.Rotator(roll=0.0, pitch=0.0, yaw=PLATE_YAW))
        plate.set_actor_label("RND_video")
        comp = plate.get_editor_property("media_plate_component")
        res = unreal.MediaPlateResource()
        res.set_editor_property("type", unreal.MediaPlateResourceType.EXTERNAL)
        res.set_editor_property("external_media_path", os.path.join(ROOT, VIDEO))
        comp.set_editor_property("media_plate_resource", res)
        comp.set_is_aspect_ratio_auto(False)
        comp.set_editor_property("loop", True)
        # SM_MediaPlateScreen is a 100x100 plane in local Y/Z.
        plate.get_editor_property("static_mesh_component").set_relative_scale3d(
            unreal.Vector(1.0, SCREEN_W_CM / 100.0, SCREEN_H_CM / 100.0))

    cls = unreal.load_object(None, "%s/%s.%s_C" % (ASSET_DIR, ASSET_NAME, ASSET_NAME))
    dcra = (actors.spawn_actor_from_class(cls, *keep_transform) if keep_transform
            else actors.spawn_actor_from_class(cls, O))
    dcra.set_actor_label(ASSET_NAME)
    # External-config override only replaces viewports, so the mask goes on the instance.
    node = dcra.get_editor_property("current_config_data").cluster.nodes["node_0"]
    remap = node.output_remap
    remap.enable, remap.external_file = ROUNDED, MASK_PATH
    remap.data_source = unreal.DisplayClusterConfigurationFramePostProcess_OutputRemapSource.EXTERNAL_FILE
    node.output_remap = remap
    for c in dcra.get_components_by_class(unreal.DisplayClusterCameraComponent):
        if c.get_name() == EYE_NAME:
            c.set_relative_location(unreal.Vector(0, 0, 0), False, False)
    for c in dcra.get_components_by_class(unreal.DisplayClusterScreenComponent):
        if c.get_name() == SCREEN_NAME:
            c.set_relative_location_and_rotation(unreal.Vector(EYE_DIST_CM, 0, SCREEN_DZ_CM),
                                                 unreal.Rotator(0, 0, 0), False, False)
            c.set_relative_scale3d(unreal.Vector(1.0, SCREEN_W_CM, SCREEN_H_CM))
    if not unreal.get_editor_subsystem(unreal.LevelEditorSubsystem).save_current_level():
        # Error Code 32 in the log = another editor has Round.umap open. Open a
        # different level there (or run this script from that editor's Python console).
        raise RuntimeError("Round.umap save FAILED - level not updated (is it open in another editor?)")
    unreal.log("round rig ready: DCRA at %s = viewer's eye (%s), wall at %g cm"
               % (dcra.get_actor_location(), "kept from level" if keep_transform else "RIG_ORIGIN", EYE_DIST_CM))


def main():
    demo()
    os.makedirs(os.path.dirname(CFG_PATH), exist_ok=True)
    with open(CFG_PATH, "w") as f:
        json.dump(build_config(), f, indent=2)
    with open(os.path.join(ROOT, BAT), "w", newline="") as f:
        f.write(build_bat())
    with open(MASK_PATH, "w") as f:
        f.write(build_mask_obj())
    print("wrote " + CFG_PATH + "\nwrote " + MASK_PATH + "\nwrote " + BAT)
    try:
        import unreal  # noqa: F401
    except ImportError:
        pass
    else:
        build_level()


if __name__ == "__main__":
    main()
